### ISSUE TITLE
Cannot find module '../src/cli.js'

### ISSUE THREAD

**Issue by t-yng** [ovr/StaticScript#11]
I tried to execute, I got the following errors when I tried to execute on macOS

```
$ npm install -g static-script
$ ssc math.ts
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '../src/cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/yanagi.tomohiro/workspace/ts/StaticScript/bin/ssc:3:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by ovr** [comment]
Hey! I am working on this issue, thank you for bug reporting, I will comment back shortly, when new release will be ready!

Thanks

**Comment by ovr** [comment]
Fixed, please use latest release, you can update it by install:

```
npm install -g static-script
```

**Comment by t-yng** [comment]
Thank you for your fix, now it works fine.
